// IELTS Vocabulary Data classified by topic for EnglishFree
// Includes UK/US IPA fields and illustrative Unsplash photo IDs.

const VOCABULARY_DATA = [
  {
    "word": "Euphoric",
    "partOfSpeech": "adjective",
    "ipaUk": "/juːˈfɒr.ɪk/",
    "ipaUs": "/juːˈfɔːr.ɪk/",
    "translation": "Hạnh phúc tột độ, hưng phấn",
    "example": "The team was euphoric after winning the championship.",
    "exampleVi": "Đội bóng đã vô cùng phấn khích sau khi giành chức vô địch.",
    "imageId": "photo-1516450360452-9312f5e86fc7",
    "topic": "emotion"
  },
  {
    "word": "Apprehensive",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˌæp.rɪˈhen.sɪv/",
    "ipaUs": "/ˌæp.rəˈhen.sɪv/",
    "translation": "Lo lắng, e ngại (về tương lai)",
    "example": "Many students feel apprehensive about their upcoming IELTS exams.",
    "exampleVi": "Nhiều học sinh cảm thấy lo lắng về kỳ thi IELTS sắp tới của họ.",
    "imageId": "photo-1516321497487-e288fb19713f",
    "topic": "emotion"
  },
  {
    "word": "Melancholy",
    "partOfSpeech": "noun / adjective",
    "ipaUk": "/ˈmel.əŋ.kɒl.i/",
    "ipaUs": "/ˈmel.əŋ.kɑːl.i/",
    "translation": "Sự u sầu, u uất",
    "example": "A feeling of melancholy descended on him as he looked at the old photographs.",
    "exampleVi": "Một cảm giác u sầu bao trùm lấy anh khi nhìn những bức ảnh cũ.",
    "imageId": "photo-1498330177096-689e3fb901ca",
    "topic": "emotion"
  },
  {
    "word": "Indifferent",
    "partOfSpeech": "adjective",
    "ipaUk": "/ɪnˈdɪf.ər.ənt/",
    "ipaUs": "/ɪnˈdɪf.ɚ.ənt/",
    "translation": "Thờ ơ, vô tâm",
    "example": "The government cannot remain indifferent to the plight of the homeless.",
    "exampleVi": "Chính phủ không thể tiếp tục thờ ơ trước hoàn cảnh khó khăn của những người vô gia cư.",
    "imageId": "photo-1507679799987-c73779587ccf",
    "topic": "emotion"
  },
  {
    "word": "Exasperated",
    "partOfSpeech": "adjective",
    "ipaUk": "/ɪɡˈzɑː.spə.reɪ.tɪd/",
    "ipaUs": "/ɪɡˈzæs.pə.reɪ.t̬ɪd/",
    "translation": "Bực tức, phát cáu",
    "example": "He became exasperated by the constant interruptions during his speech.",
    "exampleVi": "Anh ấy trở nên bực tức vì những sự ngắt quãng liên tục trong suốt bài phát biểu.",
    "imageId": "photo-1534528741775-53994a69daeb",
    "topic": "emotion"
  },
  {
    "word": "Ambivalent",
    "partOfSpeech": "adjective",
    "ipaUk": "/æmˈbɪv.ə.lənt/",
    "ipaUs": "/æmˈbɪv.ə.lənt/",
    "translation": "Mâu thuẫn trong cảm xúc",
    "example": "She felt ambivalent about leaving her hometown for a career opportunity abroad.",
    "exampleVi": "Cô cảm thấy mâu thuẫn khi rời bỏ quê hương để đi tìm cơ hội nghề nghiệp ở nước ngoài.",
    "imageId": "photo-1516246843873-9d12356b6ffd",
    "topic": "emotion"
  },
  {
    "word": "Empathetic",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˌem.pəˈθet.ɪk/",
    "ipaUs": "/ˌem.pəˈθet̬.ɪk/",
    "translation": "Thấu cảm, đồng cảm",
    "example": "Good medical practitioners are not only skilled but also empathetic towards their patients.",
    "exampleVi": "Các y bác sĩ giỏi không chỉ có tay nghề cao mà còn biết đồng cảm với bệnh nhân.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "emotion"
  },
  {
    "word": "Despondent",
    "partOfSpeech": "adjective",
    "ipaUk": "/dɪˈspɒn.dənt/",
    "ipaUs": "/dɪˈspɑːn.dənt/",
    "translation": "Nản lòng, tuyệt vọng",
    "example": "She grew despondent after failing to find a job for six months.",
    "exampleVi": "Cô ấy trở nên nản lòng sau sáu tháng không tìm được việc làm.",
    "imageId": "photo-1489440543286-a69330151c0b",
    "topic": "emotion"
  },
  {
    "word": "Gratitude",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈɡræt.ɪ.tʃuːd/",
    "ipaUs": "/ˈɡræt̬.ə.tuːd/",
    "translation": "Lòng biết ơn",
    "example": "Expressing gratitude daily can significantly enhance a person’s emotional well-being.",
    "exampleVi": "Bộc lộ lòng biết ơn hàng ngày có thể cải thiện đáng kể sức khỏe cảm xúc của một người.",
    "imageId": "photo-1502082553048-f009c37129b9",
    "topic": "emotion"
  },
  {
    "word": "Jealousy",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈdʒel.ə.si/",
    "ipaUs": "/ˈdʒel.ə.si/",
    "translation": "Sự ghen tị",
    "example": "Extreme jealousy can easily tear apart a long-term relationship.",
    "exampleVi": "Sự ghen tị thái quá có thể dễ dàng phá vỡ một mối quan hệ lâu dài.",
    "imageId": "photo-1522075469751-3a6694fb2f61",
    "topic": "emotion"
  },
  {
    "word": "Anxiety",
    "partOfSpeech": "noun",
    "ipaUk": "/æŋˈzaɪ.ə.ti/",
    "ipaUs": "/æŋˈzaɪ.ə.t̬i/",
    "translation": "Sự lo âu, mối lo ngại",
    "example": "Prolonged exposure to high-pressure environments can trigger severe anxiety.",
    "exampleVi": "Tiếp xúc lâu dài với môi trường áp lực cao có thể dẫn đến chứng lo âu nghiêm trọng.",
    "imageId": "photo-1518495973542-4542c06a5843",
    "topic": "emotion"
  },
  {
    "word": "Resentment",
    "partOfSpeech": "noun",
    "ipaUk": "/rɪˈzent.mənt/",
    "ipaUs": "/rɪˈzent.mənt/",
    "translation": "Sự phẫn uất, oán hận",
    "example": "She harbored resentment against her boss for passing her over for promotion.",
    "exampleVi": "Cô ấy nuôi lòng oán hận đối với sếp vì đã không cân nhắc cô cho đợt thăng chức.",
    "imageId": "photo-1552053831-71594a27632d",
    "topic": "emotion"
  },
  {
    "word": "Embarrassment",
    "partOfSpeech": "noun",
    "ipaUk": "/ɪmˈbær.əs.mənt/",
    "ipaUs": "/ɪmˈber.əs.mənt/",
    "translation": "Sự ngượng ngùng, xấu hổ",
    "example": "He turned red with embarrassment when his voice cracked during the presentation.",
    "exampleVi": "Anh ấy đỏ mặt vì ngượng ngùng khi giọng của mình bị vỡ trong suốt bài thuyết trình.",
    "imageId": "photo-1501196354995-cbb51c65aaea",
    "topic": "emotion"
  },
  {
    "word": "Compassion",
    "partOfSpeech": "noun",
    "ipaUk": "/kəmˈpæʃ.ən/",
    "ipaUs": "/kəmˈpæʃ.ən/",
    "translation": "Lòng trắc ẩn",
    "example": "The refugee crisis requires global leaders to act with great compassion.",
    "exampleVi": "Cuộc khủng hoảng người tị nạn đòi hỏi các nhà lãnh đạo toàn cầu phải hành động với lòng trắc ẩn.",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "emotion"
  },
  {
    "word": "Contentment",
    "partOfSpeech": "noun",
    "ipaUk": "/kənˈtent.mənt/",
    "ipaUs": "/kənˈtent.mənt/",
    "translation": "Sự mãn nguyện",
    "example": "True contentment comes from within rather than from material wealth.",
    "exampleVi": "Sự mãn nguyện đích thực đến từ bên trong hơn là từ của cải vật chất.",
    "imageId": "photo-1470240731273-7821a6eeb6bd",
    "topic": "emotion"
  },
  {
    "word": "Biodiversity",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/",
    "ipaUs": "/ˌbaɪ.oʊ.daɪˈvɝː.sə.t̬i/",
    "translation": "Đa dạng sinh học",
    "example": "Deforestation poses a critical threat to global biodiversity.",
    "exampleVi": "Nạn phá rừng đe dọa nghiêm trọng đến đa dạng sinh học toàn cầu.",
    "imageId": "photo-1500485035595-cbe6f645feb1",
    "topic": "environment"
  },
  {
    "word": "Conservation",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌɒn.səˈveɪ.ʃən/",
    "ipaUs": "/ˌkɑːn.sɚˈveɪ.ʃən/",
    "translation": "Sự bảo tồn (thiên nhiên)",
    "example": "Environmental conservation requires international cooperation and funding.",
    "exampleVi": "Bảo tồn môi trường đòi hỏi sự hợp tác và nguồn vốn quốc tế.",
    "imageId": "photo-1466692476868-aef1dfb1e735",
    "topic": "environment"
  },
  {
    "word": "Depletion",
    "partOfSpeech": "noun",
    "ipaUk": "/dɪˈpliː.ʃən/",
    "ipaUs": "/dɪˈpliː.ʃən/",
    "translation": "Sự suy kiệt, cạn kiệt",
    "example": "The rapid depletion of natural resources is a major concern for scientists.",
    "exampleVi": "Sự cạn kiệt nhanh chóng các tài nguyên thiên nhiên là mối lo ngại lớn của các nhà khoa học.",
    "imageId": "photo-1504384308090-c894fdcc538d",
    "topic": "environment"
  },
  {
    "word": "Ecological",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˌiː.kəˈlɒdʒ.ɪ.kəl/",
    "ipaUs": "/ˌiː.kəˈlɑː.dʒɪ.kəl/",
    "translation": "Thuộc về sinh thái",
    "example": "Oil spills can cause long-term ecological damage to marine habitats.",
    "exampleVi": "Các vụ tràn dầu có thể gây ra thiệt hại sinh thái lâu dài cho môi trường sống dưới biển.",
    "imageId": "photo-1470071459604-3b5ec3a7fe05",
    "topic": "environment"
  },
  {
    "word": "Mitigate",
    "partOfSpeech": "verb",
    "ipaUk": "/ˈmɪt.ɪ.ɡeɪt/",
    "ipaUs": "/ˈmɪt̬.ə.ɡeɪt/",
    "translation": "Giảm thiểu, làm dịu bớt",
    "example": "Governments must take action to mitigate the effects of climate change.",
    "exampleVi": "Chính phủ phải hành động để giảm thiểu những tác động của biến đổi khí hậu.",
    "imageId": "photo-1468245856972-a0333f3f8293",
    "topic": "environment"
  },
  {
    "word": "Sustainability",
    "partOfSpeech": "noun",
    "ipaUk": "/səˌsteɪ.nəˈbɪl.ə.ti/",
    "ipaUs": "/səˌsteɪ.nəˈbɪl.ə.t̬i/",
    "translation": "Sự phát triển bền vững",
    "example": "Modern industries are shifting towards sustainability to protect the planet.",
    "exampleVi": "Các ngành công nghiệp hiện đại đang dịch chuyển hướng tới sự bền vững để bảo vệ hành tinh.",
    "imageId": "photo-1532601224476-15c79f2f7a51",
    "topic": "environment"
  },
  {
    "word": "Contamination",
    "partOfSpeech": "noun",
    "ipaUk": "/kənˌtæm.ɪˈneɪ.ʃən/",
    "ipaUs": "/kənˌtæm.əˈneɪ.ʃən/",
    "translation": "Sự ô nhiễm, chất độc hại",
    "example": "The contamination of local water supplies has led to severe health issues.",
    "exampleVi": "Sự ô nhiễm nguồn cấp nước địa phương đã dẫn đến các vấn đề sức khỏe nghiêm trọng.",
    "imageId": "photo-1618477388954-7852f32655ec",
    "topic": "environment"
  },
  {
    "word": "Combustion",
    "partOfSpeech": "noun",
    "ipaUk": "/kəmˈbʌs.tʃən/",
    "ipaUs": "/kəmˈbʌs.tʃən/",
    "translation": "Sự đốt cháy (nhiên liệu)",
    "example": "The combustion of fossil fuels releases carbon dioxide into the atmosphere.",
    "exampleVi": "Việc đốt cháy nhiên liệu hóa thạch giải phóng khí carbon dioxide vào khí quyển.",
    "imageId": "photo-1518152006812-edab29b069ac",
    "topic": "environment"
  },
  {
    "word": "Desertification",
    "partOfSpeech": "noun",
    "ipaUk": "/dɪˌzɜː.tɪ.fɪˈkeɪ.ʃən/",
    "ipaUs": "/dɪˌzɝː.t̬ə.fəˈkeɪ.ʃən/",
    "translation": "Quá trình sa mạc hóa",
    "example": "Overgrazing and deforestation are the primary drivers of desertification.",
    "exampleVi": "Chăn thả quá mức và phá rừng là những nguyên nhân chính dẫn đến sa mạc hóa.",
    "imageId": "photo-1509316975850-ff9c5deb0cd9",
    "topic": "environment"
  },
  {
    "word": "Catastrophic",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˌcæt.əˈstrɒf.ɪk/",
    "ipaUs": "/ˌkæt̬.əˈstrɑː.fɪk/",
    "translation": "Thảm khốc, thảm họa",
    "example": "Rising sea levels could have catastrophic consequences for coastal cities.",
    "exampleVi": "Mực nước biển dâng cao có thể gây ra những hậu quả thảm khốc cho các thành phố ven biển.",
    "imageId": "photo-1480074568708-e7b720bb3f09",
    "topic": "environment"
  },
  {
    "word": "Ecosystem",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈiː.kəʊˌsɪs.təm/",
    "ipaUs": "/ˈiː.koʊˌsɪs.təm/",
    "translation": "Hệ sinh thái",
    "example": "Introducing foreign species can disrupt the delicate balance of the ecosystem.",
    "exampleVi": "Việc đưa các loài ngoại lai vào có thể làm đảo lộn sự cân bằng mỏng manh của hệ sinh thái.",
    "imageId": "photo-1547036967-23d11aacaee0",
    "topic": "environment"
  },
  {
    "word": "Inundate",
    "partOfSpeech": "verb",
    "ipaUk": "/ˈɪn.ʌn.deɪt/",
    "ipaUs": "/ˈɪn.ʌn.deɪt/",
    "translation": "Ngập lụt, tràn ngập nước",
    "example": "Heavy monsoons frequently inundate agricultural lands in southeast Asia.",
    "exampleVi": "Gió mùa lớn thường xuyên làm ngập lụt các vùng đất nông nghiệp ở Đông Nam Á.",
    "imageId": "photo-1545128485-c400e7702796",
    "topic": "environment"
  },
  {
    "word": "Precipitation",
    "partOfSpeech": "noun",
    "ipaUk": "/prɪˌsɪp.ɪˈteɪ.ʃən/",
    "ipaUs": "/prɪˌsɪp.əˈteɪ.ʃən/",
    "translation": "Lượng mưa, tuyết rơi",
    "example": "Changes in global precipitation patterns can cause severe droughts in some regions.",
    "exampleVi": "Sự thay đổi trong các mô hình lượng mưa toàn cầu có thể gây ra hạn hán ở một số vùng.",
    "imageId": "photo-1534274988757-a28bf1a57c17",
    "topic": "environment"
  },
  {
    "word": "Overexploitation",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌəʊ.vər.ek.splɔɪˈteɪ.ʃən/",
    "ipaUs": "/ˌoʊ.vɚ.ek.splɔɪˈteɪ.ʃən/",
    "translation": "Khai thác quá mức",
    "example": "The overexploitation of fish stocks has threatened marine biodiversity.",
    "exampleVi": "Việc khai thác quá mức nguồn cá dự trữ đã đe dọa đa dạng sinh học biển.",
    "imageId": "photo-1498654896293-37aacf113fd9",
    "topic": "environment"
  },
  {
    "word": "Permafrost",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈpɜː.mə.frɒst/",
    "ipaUs": "/ˈpɝː.mə.frɑːst/",
    "translation": "Tầng đất đóng băng vĩnh cửu",
    "example": "The melting of permafrost releases large amounts of methane gas.",
    "exampleVi": "Sự tan chảy của tầng đất đóng băng vĩnh cửu giải phóng một lượng lớn khí mê-tan.",
    "imageId": "photo-1551818255-e6e10975bc17",
    "topic": "environment"
  },
  {
    "word": "Automation",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌɔː.təˈmeɪ.ʃən/",
    "ipaUs": "/ˌaʊ.t̬əˈmeɪ.ʃən/",
    "translation": "Sự tự động hóa",
    "example": "Automation in manufacturing has reduced the need for manual labor.",
    "exampleVi": "Tự động hóa trong sản xuất đã giảm thiểu nhu cầu lao động chân tay.",
    "imageId": "photo-1485827404703-89b55fcc595e",
    "topic": "technology"
  },
  {
    "word": "Accessibility",
    "partOfSpeech": "noun",
    "ipaUk": "/əkˌses.əˈbɪl.ə.ti/",
    "ipaUs": "/əkˌses.əˈbɪl.ə.t̬i/",
    "translation": "Khả năng tiếp cận",
    "example": "The internet has greatly improved the accessibility of higher education.",
    "exampleVi": "Internet đã cải thiện đáng kể khả năng tiếp cận giáo dục đại học.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "technology"
  },
  {
    "word": "Cybersecurity",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌsaɪ.bə.sɪˈkjʊə.rə.ti/",
    "ipaUs": "/ˌsaɪ.bɚ.sɪˈkjʊr.ə.t̬i/",
    "translation": "An ninh mạng",
    "example": "Governments need to invest heavily in cybersecurity to protect national secrets.",
    "exampleVi": "Chính phủ cần đầu tư mạnh vào an ninh mạng để bảo vệ các bí mật quốc gia.",
    "imageId": "photo-1550751827-4bd374c3f58b",
    "topic": "technology"
  },
  {
    "word": "Obsolete",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˈɒb.səl.iːt/",
    "ipaUs": "/ˌɑːb.səˈliːt/",
    "translation": "Lỗi thời, cổ xưa",
    "example": "The rapid pace of technological change makes older devices obsolete quickly.",
    "exampleVi": "Tốc độ thay đổi công nghệ nhanh chóng khiến các thiết bị cũ bị lỗi thời nhanh chóng.",
    "imageId": "photo-1544006659-f0b21f02473c",
    "topic": "technology"
  },
  {
    "word": "Innovation",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌɪn.əˈveɪ.ʃən/",
    "ipaUs": "/ˌɪn.əˈveɪ.ʃən/",
    "translation": "Sự đổi mới, cách tân",
    "example": "Continuous innovation is key to maintaining a competitive edge in business.",
    "exampleVi": "Đổi mới liên tục là chìa khóa để duy trì lợi thế cạnh tranh trong kinh doanh.",
    "imageId": "photo-1451187580459-43490279c0fa",
    "topic": "technology"
  },
  {
    "word": "Inequality",
    "partOfSpeech": "noun",
    "ipaUk": "/ˌɪn.ɪˈkwɒl.ə.ti/",
    "ipaUs": "/ˌɪn.ɪˈkwɑː.lə.t̬i/",
    "translation": "Sự bất bình đẳng",
    "example": "The digital divide can exacerbate social and economic inequality.",
    "exampleVi": "Khoảng cách kỹ thuật số có thể làm trầm trọng thêm tình trạng bất bình đẳng kinh tế và xã hội.",
    "imageId": "photo-1450133064473-71024230f91b",
    "topic": "technology"
  },
  {
    "word": "Infrastructure",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈɪn.frəˌstrʌk.tʃər/",
    "ipaUs": "/ˈɪn.frəˌstrʌk.tʃɚ/",
    "translation": "Cơ sở hạ tầng",
    "example": "Modern cities require a reliable digital infrastructure to support smart services.",
    "exampleVi": "Các thành phố hiện đại đòi hỏi một cơ sở hạ tầng kỹ thuật số đáng tin cậy để hỗ trợ dịch vụ thông minh.",
    "imageId": "photo-1541888946425-d81bb19240f5",
    "topic": "technology"
  },
  {
    "word": "Prevalent",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˈprev.əl.ənt/",
    "ipaUs": "/ˈprev.əl.ənt/",
    "translation": "Phổ biến, thịnh hành",
    "example": "Social media addiction has become prevalent among adolescents today.",
    "exampleVi": "Nghiện mạng xã hội đã trở nên phổ biến ở thanh thiếu niên ngày nay.",
    "imageId": "photo-1515187029135-18ee286d815b",
    "topic": "technology"
  },
  {
    "word": "Skepticism",
    "partOfSpeech": "noun",
    "ipaUk": "/ˈskep.tɪ.sɪ.zəm/",
    "ipaUs": "/ˈskep.tɪ.sɪ.zəm/",
    "translation": "Sự hoài nghi",
    "example": "There is growing skepticism regarding the safety of AI-driven vehicles.",
    "exampleVi": "Ngày càng có nhiều sự hoài nghi về độ an toàn của xe tự lái bằng trí tuệ nhân tạo.",
    "imageId": "photo-1507679799987-c73779587ccf",
    "topic": "technology"
  },
  {
    "word": "Demographic",
    "partOfSpeech": "noun / adjective",
    "ipaUk": "/ˌdem.əˈɡræf.ɪk/",
    "ipaUs": "/ˌdem.əˈɡræf.ɪk/",
    "translation": "Nhóm dân số, nhân khẩu học",
    "example": "Marketers target the young demographic because of their high spending power.",
    "exampleVi": "Các nhà tiếp thị nhắm mục tiêu vào nhóm khách hàng trẻ tuổi vì khả năng chi tiêu cao của họ.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "technology"
  },
  {
    "word": "Collaborate",
    "partOfSpeech": "verb",
    "ipaUk": "/kəˈlæb.ə.reɪt/",
    "ipaUs": "/kəˈlæb.ə.reɪt/",
    "translation": "Hợp tác, phối hợp",
    "example": "Scientists from different countries collaborate to develop vaccines.",
    "exampleVi": "Các nhà khoa học từ các quốc gia khác nhau hợp tác để phát triển vắc-xin.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "technology"
  },
  {
    "word": "Virtual",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˈvɜː.tʃu.əl/",
    "ipaUs": "/ˈvɝː.tʃu.əl/",
    "translation": "Ảo (trực tuyến)",
    "example": "Virtual meetings have replaced many physical business trips.",
    "exampleVi": "Các cuộc họp ảo đã thay thế nhiều chuyến đi công tác trực tiếp.",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "technology"
  },
  {
    "word": "Disruption",
    "partOfSpeech": "noun",
    "ipaUk": "/dɪsˈrʌp.ʃən/",
    "ipaUs": "/dɪsˈrʌp.ʃən/",
    "translation": "Sự gián đoạn",
    "example": "The pandemic caused major disruption to global supply chains.",
    "exampleVi": "Đại dịch đã gây ra sự gián đoạn lớn đối với chuỗi cung ứng toàn cầu.",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "technology"
  },
  {
    "word": "Socio-economic",
    "partOfSpeech": "adjective",
    "ipaUk": "/ˌsəʊ.si.əʊ.iː.kəˈnɒm.ɪk/",
    "ipaUs": "/ˌsoʊ.si.oʊ.iː.kəˈnɑː.mɪk/",
    "translation": "Thuộc về kinh tế - xã hội",
    "example": "Technological access can bridge the gap between different socio-economic groups.",
    "exampleVi": "Tiếp cận công nghệ có thể thu hẹp khoảng cách giữa các nhóm kinh tế - xã hội khác nhau.",
    "imageId": "photo-1486406146926-c627a92ad1ab",
    "topic": "technology"
  },
  {
    "word": "Proliferation",
    "partOfSpeech": "noun",
    "ipaUk": "/prəˌlɪf.ərˈeɪ.ʃən/",
    "ipaUs": "/prəˌlɪf.əˈreɪ.ʃən/",
    "translation": "Sự bùng nổ, bùng phát nhanh",
    "example": "The proliferation of smartphones has changed how we consume information.",
    "exampleVi": "Sự bùng nổ của điện thoại thông minh đã thay đổi cách chúng ta tiếp nhận thông tin.",
    "imageId": "photo-1519389950473-47ba0277781c",
    "topic": "technology"
  },
  {
    "word": "account for",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈkaʊnt fɔːr/",
    "ipaUs": "/əˈkaʊnt fɔːr/",
    "translation": "giải thích, chiếm",
    "example": "All people who were working in the building have now been accounted for.",
    "exampleVi": "Tất cả những người làm việc trong tòa nhà hiện đã được xác nhận.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "allow for",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈlaʊ fɔːr/",
    "ipaUs": "/əˈlaʊ fɔːr/",
    "translation": "tính đến, xem xét đến",
    "example": "She allows for me to follow her.",
    "exampleVi": "Cô ấy cho phép tôi đi theo.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "ask after",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɑːsk ˈɑːftər/",
    "ipaUs": "/ɑːsk ˈɑːftər/",
    "translation": "hỏi thăm sức khỏe",
    "example": "If you want to know how he is now, you should ask after him.",
    "exampleVi": "Nếu bạn muốn biết bây giờ anh ấy thế nào, bạn nên hỏi thăm anh ấy.",
    "imageId": "photo-1507679799987-c73779587ccf",
    "topic": "phrasal-verbs"
  },
  {
    "word": "ask for",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɑːsk fɔːr/",
    "ipaUs": "/ɑːsk fɔːr/",
    "translation": "hỏi xin",
    "example": "I was driving, a man asking me for a lift.",
    "exampleVi": "Tôi đang lái xe thì một người đàn ông xin đi nhờ.",
    "imageId": "photo-1507679799987-c73779587ccf",
    "topic": "phrasal-verbs"
  },
  {
    "word": "advance on",
    "partOfSpeech": "phr v",
    "ipaUk": "/ədˈvɑːns ɒn/",
    "ipaUs": "/ədˈvɑːns ɒn/",
    "translation": "tiến lên, tấn công",
    "example": "The army began to advance on the city.",
    "exampleVi": "Quân đội bắt đầu tiến về phía thành phố.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "agree on",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈɡriː ɒn/",
    "ipaUs": "/əˈɡriː ɒn/",
    "translation": "đồng ý về",
    "example": "They agreed to meet on Sunday.",
    "exampleVi": "Họ đã đồng ý gặp nhau vào Chủ nhật.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "agree with",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈɡriː wɪð/",
    "ipaUs": "/əˈɡriː wɪð/",
    "translation": "đồng ý với",
    "example": "I agree with you.",
    "exampleVi": "Tôi đồng ý với bạn.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "answer for",
    "partOfSpeech": "phr v",
    "ipaUk": "/ˈɑːnsər fɔːr/",
    "ipaUs": "/ˈɑːnsər fɔːr/",
    "translation": "chịu trách nhiệm về",
    "example": "You have to answer for your trouble at the meeting tomorrow.",
    "exampleVi": "Bạn sẽ phải chịu trách nhiệm về những rắc rối của mình tại cuộc họp ngày mai.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "attend on",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈten ɒn/",
    "ipaUs": "/əˈten ɒn/",
    "translation": "chăm sóc, phục vụ",
    "example": "A nurse attended to his needs constantly.",
    "exampleVi": "Một y tá liên tục chăm sóc các nhu cầu của anh ấy.",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "phrasal-verbs"
  },
  {
    "word": "attend to",
    "partOfSpeech": "phr v",
    "ipaUk": "/əˈten tuː/",
    "ipaUs": "/əˈten tuː/",
    "translation": "chú ý, giải quyết",
    "example": "Doctors tried to attend to the worst injured soldiers first.",
    "exampleVi": "Các bác sĩ đã cố gắng cứu chữa những người lính bị thương nặng nhất trước.",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "phrasal-verbs"
  },
  {
    "word": "bring in",
    "partOfSpeech": "phr v",
    "ipaUk": "/brɪŋ ɪn/",
    "ipaUs": "/brɪŋ ɪn/",
    "translation": "mang lại, giới thiệu",
    "example": "She brings in about $600 a week.",
    "exampleVi": "Cô ấy kiếm được khoảng 600 đô la một tuần.",
    "imageId": "photo-1513151233558-d860c5398176",
    "topic": "phrasal-verbs"
  },
  {
    "word": "bring up",
    "partOfSpeech": "phr v",
    "ipaUk": "/brɪŋ ʌp/",
    "ipaUs": "/brɪŋ ʌp/",
    "translation": "nuôi dưỡng, đề cập",
    "example": "An aunt brought him up.",
    "exampleVi": "Một người dì đã nuôi nấng anh ấy.",
    "imageId": "photo-1513151233558-d860c5398176",
    "topic": "phrasal-verbs"
  },
  {
    "word": "back up",
    "partOfSpeech": "phr v",
    "ipaUk": "/bæk ʌp/",
    "ipaUs": "/bæk ʌp/",
    "translation": "ủng hộ, sao lưu",
    "example": "The traffic is starting to back up on the highway.",
    "exampleVi": "Giao thông đang bắt đầu ùn ứ trên đường cao tốc.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "phrasal-verbs"
  },
  {
    "word": "belong to",
    "partOfSpeech": "phr v",
    "ipaUk": "/bɪˈlɒŋ tuː/",
    "ipaUs": "/bɪˈlɒŋ tuː/",
    "translation": "thuộc về",
    "example": "Does this book belong to you or to Sarah?",
    "exampleVi": "Cuốn sách này thuộc về bạn hay của Sarah?",
    "imageId": "photo-1470240731273-7821a6eeb6bd",
    "topic": "phrasal-verbs"
  },
  {
    "word": "break in",
    "partOfSpeech": "phr v",
    "ipaUk": "/breɪk ɪn/",
    "ipaUs": "/breɪk ɪn/",
    "translation": "đột nhập, ngắt lời",
    "example": "As she was talking, he suddenly broke in, saying, “That’s a lie.”",
    "exampleVi": "Khi cô ấy đang nói, anh ta đột nhiên xen vào: \"Đó là lời nói dối.\"",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "break away",
    "partOfSpeech": "phr v",
    "ipaUk": "/breɪk əˈweɪ/",
    "ipaUs": "/breɪk əˈweɪ/",
    "translation": "trốn thoát, rời bỏ",
    "example": "He grabbed her, but she managed to break away.",
    "exampleVi": "Anh ta chộp lấy cô, nhưng cô đã xoay xở trốn thoát được.",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "break down",
    "partOfSpeech": "phr v",
    "ipaUk": "/breɪk daʊn/",
    "ipaUs": "/breɪk daʊn/",
    "translation": "hỏng, suy sụp",
    "example": "Oh no – has your washing machine broken down again?",
    "exampleVi": "Ôi không – máy giặt của bạn lại bị hỏng nữa rồi à?",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "break up",
    "partOfSpeech": "phr v",
    "ipaUk": "/breɪk ʌp/",
    "ipaUs": "/breɪk ʌp/",
    "translation": "chia tay, tan rã",
    "example": "He moved away after the break-up of his marriage.",
    "exampleVi": "Anh ấy đã chuyển đi nơi khác sau khi cuộc hôn nhân tan vỡ.",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "break off",
    "partOfSpeech": "phr v",
    "ipaUk": "/breɪk ɒf/",
    "ipaUs": "/breɪk ɒf/",
    "translation": "đột ngột dừng lại, bẻ gãy",
    "example": "The narrator broke off in the middle of the story.",
    "exampleVi": "Người kể chuyện đột ngột dừng lại ở giữa câu chuyện.",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "bring down",
    "partOfSpeech": "phr v",
    "ipaUk": "/brɪŋ daʊn/",
    "ipaUs": "/brɪŋ daʊn/",
    "translation": "hạ xuống, đánh sập",
    "example": "The old building finally was brought down.",
    "exampleVi": "Tòa nhà cũ cuối cùng đã bị đánh sập.",
    "imageId": "photo-1513151233558-d860c5398176",
    "topic": "phrasal-verbs"
  },
  {
    "word": "bring out",
    "partOfSpeech": "phr v",
    "ipaUk": "/brɪŋ aʊt/",
    "ipaUs": "/brɪŋ aʊt/",
    "translation": "làm nổi bật, đưa ra",
    "example": "The artists' greatest wish was to bring out the best in their admirers.",
    "exampleVi": "Ước nguyện lớn nhất của các nghệ sĩ là khơi gợi điều tốt đẹp nhất ở những người ngưỡng mộ họ.",
    "imageId": "photo-1513151233558-d860c5398176",
    "topic": "phrasal-verbs"
  },
  {
    "word": "bring off",
    "partOfSpeech": "phr v",
    "ipaUk": "/brɪŋ ɒf/",
    "ipaUs": "/brɪŋ ɒf/",
    "translation": "thành công, hoàn thành",
    "example": "England was close to victory, but they couldn't quite bring it off.",
    "exampleVi": "Nước Anh đã ở rất gần chiến thắng, nhưng họ đã không thể hoàn thành mục tiêu.",
    "imageId": "photo-1513151233558-d860c5398176",
    "topic": "phrasal-verbs"
  },
  {
    "word": "burn out",
    "partOfSpeech": "phr v",
    "ipaUk": "/bɜːn aʊt/",
    "ipaUs": "/bɜːn aʊt/",
    "translation": "kiệt sức, cháy trụi",
    "example": "Everyone in the building was scattered because an apartment burned out.",
    "exampleVi": "Mọi người trong tòa nhà đã chạy tán loạn vì một căn hộ bị cháy rụi.",
    "imageId": "photo-1518152006812-edab29b069ac",
    "topic": "phrasal-verbs"
  },
  {
    "word": "call off",
    "partOfSpeech": "phr v",
    "ipaUk": "/kɔːl ɒf/",
    "ipaUs": "/kɔːl ɒf/",
    "translation": "hủy bỏ",
    "example": "Union leaders called the strike off at the last minute.",
    "exampleVi": "Các nhà lãnh đạo công đoàn đã hủy bỏ cuộc đình công vào phút cuối.",
    "imageId": "photo-1516321497487-e288fb19713f",
    "topic": "phrasal-verbs"
  },
  {
    "word": "come up with",
    "partOfSpeech": "phr v",
    "ipaUk": "/kʌm ʌp wɪð/",
    "ipaUs": "/kʌm ʌp wɪð/",
    "translation": "nghĩ ra, nảy ra",
    "example": "He came up with a great idea for the ad campaign.",
    "exampleVi": "Anh ấy đã nghĩ ra một ý tưởng tuyệt vời cho chiến dịch quảng cáo.",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "clean up",
    "partOfSpeech": "phr v",
    "ipaUk": "/kliːn ʌp/",
    "ipaUs": "/kliːn ʌp/",
    "translation": "dọn dẹp, làm sạch",
    "example": "It’s time you gave your bedroom a good clean up.",
    "exampleVi": "Đã đến lúc bạn nên dọn dẹp phòng ngủ của mình thật sạch sẽ rồi.",
    "imageId": "photo-1532601224476-15c79f2f7a51",
    "topic": "phrasal-verbs"
  },
  {
    "word": "cut down",
    "partOfSpeech": "phr v",
    "ipaUk": "/kʌt daʊn/",
    "ipaUs": "/kʌt daʊn/",
    "translation": "cắt giảm, chặt",
    "example": "She used to work 50 hours a week, but recently she’s cut down.",
    "exampleVi": "Cô ấy từng làm việc 50 giờ một tuần, nhưng gần đây cô ấy đã cắt giảm.",
    "imageId": "photo-1541888946425-d81bb19240f5",
    "topic": "phrasal-verbs"
  },
  {
    "word": "catch up with",
    "partOfSpeech": "phr v",
    "ipaUk": "/kætʃ ʌp wɪð/",
    "ipaUs": "/kætʃ ʌp wɪð/",
    "translation": "bắt kịp, đuổi kịp",
    "example": "His lies will catch up with him one day.",
    "exampleVi": "Những lời nói dối của anh ta sẽ có ngày phải trả giá.",
    "imageId": "photo-1515187029135-18ee286d815b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "come about",
    "partOfSpeech": "phr v",
    "ipaUk": "/kʌm əˈbaʊt/",
    "ipaUs": "/kʌm əˈbaʊt/",
    "translation": "xảy ra",
    "example": "How did the problem come about in the first place?",
    "exampleVi": "Làm thế nào mà vấn đề này lại xảy ra ngay từ đầu?",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "check in",
    "partOfSpeech": "phr v",
    "ipaUk": "/tʃek ɪn/",
    "ipaUs": "/tʃek ɪn/",
    "translation": "đăng ký vào, nhận phòng",
    "example": "Passengers are requested to check in two hours before the flight.",
    "exampleVi": "Hành khách được yêu cầu làm thủ tục trước chuyến bay hai giờ.",
    "imageId": "photo-1550751827-4bd374c3f58b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "check out",
    "partOfSpeech": "phr v",
    "ipaUk": "/tʃek aʊt/",
    "ipaUs": "/tʃek aʊt/",
    "translation": "trả phòng, thanh toán",
    "example": "Please remember to leave your room keys at reception when you check out.",
    "exampleVi": "Xin nhớ để lại chìa khóa phòng tại quầy lễ tân khi bạn trả phòng.",
    "imageId": "photo-1550751827-4bd374c3f58b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "call up",
    "partOfSpeech": "phr v",
    "ipaUk": "/kɔːl ʌp/",
    "ipaUs": "/kɔːl ʌp/",
    "translation": "gọi điện, gọi nhập ngũ",
    "example": "He used to call me up in the middle of the night.",
    "exampleVi": "Anh ấy thường gọi điện cho tôi vào giữa đêm.",
    "imageId": "photo-1516321497487-e288fb19713f",
    "topic": "phrasal-verbs"
  },
  {
    "word": "carry out",
    "partOfSpeech": "phr v",
    "ipaUk": "/ˈkæri aʊt/",
    "ipaUs": "/ˈkæri aʊt/",
    "translation": "thực hiện, tiến hành",
    "example": "I was elected to carry out a program, the governor said.",
    "exampleVi": "Thống đốc cho biết: \"Tôi được bầu ra để thực hiện một chương trình.\"",
    "imageId": "photo-1486406146926-c627a92ad1ab",
    "topic": "phrasal-verbs"
  },
  {
    "word": "come apart",
    "partOfSpeech": "phr v",
    "ipaUk": "/kʌm əˈpɑːt/",
    "ipaUs": "/kʌm əˈpɑːt/",
    "translation": "rã ra, vỡ vụn",
    "example": "I picked up the book and it came apart in my hands.",
    "exampleVi": "Tôi nhặt cuốn sách lên và nó rã ra trên tay tôi.",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "dress up",
    "partOfSpeech": "phr v",
    "ipaUk": "/dres ʌp/",
    "ipaUs": "/dres ʌp/",
    "translation": "ăn diện, mặc đẹp",
    "example": "You don’t need to dress up to go to the mall.",
    "exampleVi": "Bạn không cần phải diện đồ đẹp để đi đến trung tâm thương mại đâu.",
    "imageId": "photo-1516450360452-9312f5e86fc7",
    "topic": "phrasal-verbs"
  },
  {
    "word": "drop by",
    "partOfSpeech": "phr v",
    "ipaUk": "/drɒp baɪ/",
    "ipaUs": "/drɒp baɪ/",
    "translation": "ghé thăm, tạt qua",
    "example": "I dropped in on George on my way home from school.",
    "exampleVi": "Tôi đã ghé vào thăm George trên đường đi học về.",
    "imageId": "photo-1498330177096-689e3fb901ca",
    "topic": "phrasal-verbs"
  },
  {
    "word": "delight in",
    "partOfSpeech": "phr v",
    "ipaUk": "/dɪˈlaɪt ɪn/",
    "ipaUs": "/dɪˈlaɪt ɪn/",
    "translation": "thích thú với",
    "example": "My brother always delights in telling me when I make a mistake.",
    "exampleVi": "Anh trai tôi luôn thích thú chỉ ra cho tôi thấy khi tôi mắc sai lầm.",
    "imageId": "photo-1470240731273-7821a6eeb6bd",
    "topic": "phrasal-verbs"
  },
  {
    "word": "die away",
    "partOfSpeech": "phr v",
    "ipaUk": "/daɪ əˈweɪ/",
    "ipaUs": "/daɪ əˈweɪ/",
    "translation": "tắt dần, nhỏ dần",
    "example": "The last notes die away and the audience burst into applause.",
    "exampleVi": "Những nốt nhạc cuối cùng tắt dần và khán giả bùng nổ trong tiếng vỗ tay.",
    "imageId": "photo-1504384308090-c894fdcc538d",
    "topic": "phrasal-verbs"
  },
  {
    "word": "die down",
    "partOfSpeech": "phr v",
    "ipaUk": "/daɪ daʊn/",
    "ipaUs": "/daɪ daʊn/",
    "translation": "dịu đi, lắng xuống",
    "example": "The fire began to die down after the rain started.",
    "exampleVi": "Ngọn lửa bắt đầu dịu dần sau khi cơn mưa bắt đầu.",
    "imageId": "photo-1504384308090-c894fdcc538d",
    "topic": "phrasal-verbs"
  },
  {
    "word": "die for",
    "partOfSpeech": "phr v",
    "ipaUk": "/daɪ fɔːr/",
    "ipaUs": "/daɪ fɔːr/",
    "translation": "rất muốn, thèm chết được",
    "example": "I'm dying for the weekend - this week's been so hard.",
    "exampleVi": "Tôi rất mong đợi đến cuối tuần - tuần này thật là vất vả.",
    "imageId": "photo-1504384308090-c894fdcc538d",
    "topic": "phrasal-verbs"
  },
  {
    "word": "drop off",
    "partOfSpeech": "phr v",
    "ipaUk": "/drɒp ɒf/",
    "ipaUs": "/drɒp ɒf/",
    "translation": "ngủ thiếp đi, giảm đi",
    "example": "I dropped off during the play and woke up when it ended.",
    "exampleVi": "Tôi ngủ thiếp đi trong suốt vở kịch và thức dậy khi nó kết thúc.",
    "imageId": "photo-1498330177096-689e3fb901ca",
    "topic": "phrasal-verbs"
  },
  {
    "word": "fall down",
    "partOfSpeech": "phr v",
    "ipaUk": "/fɔːl daʊn/",
    "ipaUs": "/fɔːl daʊn/",
    "translation": "ngã xuống, đổ sập",
    "example": "Our apple tree fell down in the storm.",
    "exampleVi": "Cây táo của chúng tôi đã bị đổ trong trận bão.",
    "imageId": "photo-1480074568708-e7b720bb3f09",
    "topic": "phrasal-verbs"
  },
  {
    "word": "fall back",
    "partOfSpeech": "phr v",
    "ipaUk": "/fɔːl bæk/",
    "ipaUs": "/fɔːl bæk/",
    "translation": "rút lui, lùi lại",
    "example": "The army fell back after losing the battle.",
    "exampleVi": "Quân đội đã rút lui sau khi thua trận.",
    "imageId": "photo-1480074568708-e7b720bb3f09",
    "topic": "phrasal-verbs"
  },
  {
    "word": "fall for",
    "partOfSpeech": "phr v",
    "ipaUk": "/fɔːl fɔːr/",
    "ipaUs": "/fɔːl fɔːr/",
    "translation": "yêu thích, bị lừa bởi",
    "example": "He fell for her the moment their eyes met.",
    "exampleVi": "Anh ấy đã yêu cô ấy ngay từ khoảnh khắc mắt họ chạm nhau.",
    "imageId": "photo-1480074568708-e7b720bb3f09",
    "topic": "phrasal-verbs"
  },
  {
    "word": "find out",
    "partOfSpeech": "phr v",
    "ipaUk": "/faɪnd aʊt/",
    "ipaUs": "/faɪnd aʊt/",
    "translation": "tìm ra, phát hiện",
    "example": "How did you find out about the party?",
    "exampleVi": "Làm sao bạn biết được về bữa tiệc?",
    "imageId": "photo-1451187580459-43490279c0fa",
    "topic": "phrasal-verbs"
  },
  {
    "word": "face off",
    "partOfSpeech": "phr v",
    "ipaUk": "/feɪs ɒf/",
    "ipaUs": "/feɪs ɒf/",
    "translation": "đối đầu, thi đấu",
    "example": "The two rival companies will face off in court.",
    "exampleVi": "Hai công ty đối thủ sẽ đối đầu với nhau tại tòa án.",
    "imageId": "photo-1450133064473-71024230f91b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "faff about",
    "partOfSpeech": "phr v",
    "ipaUk": "/fæf əˈbaʊt/",
    "ipaUs": "/fæf əˈbaʊt/",
    "translation": "lãng phí thời gian, làm việc vớ vẩn",
    "example": "He told her to stop faffing about and make her mind up.",
    "exampleVi": "Anh ấy bảo cô ấy thôi lãng phí thời gian và hãy đưa ra quyết định.",
    "imageId": "photo-1544006659-f0b21f02473c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "grow up",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡrəʊ ʌp/",
    "ipaUs": "/ɡrəʊ ʌp/",
    "translation": "lớn lên, trưởng thành",
    "example": "What do you want to be when you grow up?",
    "exampleVi": "Bạn muốn làm nghề gì khi lớn lên?",
    "imageId": "photo-1532601224476-15c79f2f7a51",
    "topic": "phrasal-verbs"
  },
  {
    "word": "give in",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡɪv ɪn/",
    "ipaUs": "/ɡɪv ɪn/",
    "translation": "chịu thua, nộp (bài)",
    "example": "He nagged me so much for a bike that eventually I gave in.",
    "exampleVi": "Nó mè nheo đòi xe đạp nhiều quá nên cuối cùng tôi đành chịu thua.",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "phrasal-verbs"
  },
  {
    "word": "go over",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡəʊ ˈəʊvər/",
    "ipaUs": "/ɡəʊ ˈəʊvər/",
    "translation": "kiểm tra lại, đi qua",
    "example": "Let's go over the plan once more to make sure we're ready.",
    "exampleVi": "Chúng ta hãy cùng kiểm tra lại kế hoạch một lần nữa để chắc chắn rằng đã sẵn sàng.",
    "imageId": "photo-1486406146926-c627a92ad1ab",
    "topic": "phrasal-verbs"
  },
  {
    "word": "give up",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡɪv ʌp/",
    "ipaUs": "/ɡɪv ʌp/",
    "translation": "từ bỏ",
    "example": "You’ll never guess the answer – do you give up?",
    "exampleVi": "Bạn sẽ không bao giờ đoán được câu trả lời đâu - bạn có bỏ cuộc không?",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "phrasal-verbs"
  },
  {
    "word": "go up",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡəʊ ʌp/",
    "ipaUs": "/ɡəʊ ʌp/",
    "translation": "tăng lên, đi lên",
    "example": "The average cost of a new house has gone up by five percent.",
    "exampleVi": "Giá trung bình của một ngôi nhà mới đã tăng lên 5%.",
    "imageId": "photo-1486406146926-c627a92ad1ab",
    "topic": "phrasal-verbs"
  },
  {
    "word": "get about",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡet əˈbaʊt/",
    "ipaUs": "/ɡet əˈbaʊt/",
    "translation": "đi lại, lan truyền",
    "example": "I get about a lot with my job- last year I visited eleven countries.",
    "exampleVi": "Tôi đi lại rất nhiều vì công việc - năm ngoái tôi đã đi thăm mười một quốc gia.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "phrasal-verbs"
  },
  {
    "word": "get by",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡet baɪ/",
    "ipaUs": "/ɡet baɪ/",
    "translation": "xoay xở, sống sót",
    "example": "They're finding it increasingly difficult to get by lately.",
    "exampleVi": "Dạo gần đây họ đang cảm thấy ngày càng khó khăn để xoay xở cuộc sống.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "phrasal-verbs"
  },
  {
    "word": "get up",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡet ʌp/",
    "ipaUs": "/ɡet ʌp/",
    "translation": "thức dậy, đứng lên",
    "example": "I get up at seven o'clock on weekdays.",
    "exampleVi": "Tôi thức dậy lúc 7 giờ sáng vào các ngày trong tuần.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "phrasal-verbs"
  },
  {
    "word": "hold up",
    "partOfSpeech": "phr v",
    "ipaUk": "/həʊld ʌp/",
    "ipaUs": "/həʊld ʌp/",
    "translation": "trì hoãn, chống đỡ",
    "example": "I hope the repairs hold up until we can get to a garage.",
    "exampleVi": "Tôi hy vọng các mối sửa chữa sẽ chịu được cho đến khi chúng tôi tới tiệm sửa xe.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "hold on",
    "partOfSpeech": "phr v",
    "ipaUk": "/həʊld ɒn/",
    "ipaUs": "/həʊld ɒn/",
    "translation": "đợi một chút, giữ chặt",
    "example": "Hold on. I’ll be ready in just a moment.",
    "exampleVi": "Chờ chút. Tôi sẽ sẵn sàng ngay bây giờ.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "hold back",
    "partOfSpeech": "phr v",
    "ipaUk": "/həʊld bæk/",
    "ipaUs": "/həʊld bæk/",
    "translation": "kiềm chế, giữ lại",
    "example": "He held back, terrified of going into the dark room.",
    "exampleVi": "Anh ấy dừng lại, sợ hãi không dám bước vào căn phòng tối.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "hope for",
    "partOfSpeech": "phr v",
    "ipaUk": "/həʊp fɔːr/",
    "ipaUs": "/həʊp fɔːr/",
    "translation": "hy vọng về",
    "example": "I’ve repaired it as well as I can – we’ll just have to hope for the best.",
    "exampleVi": "Tôi đã sửa nó hết mức có thể rồi – chúng ta chỉ còn biết hy vọng vào điều tốt đẹp nhất.",
    "imageId": "photo-1502082553048-f009c37129b9",
    "topic": "phrasal-verbs"
  },
  {
    "word": "keep up",
    "partOfSpeech": "phr v",
    "ipaUk": "/kiːp ʌp/",
    "ipaUs": "/kiːp ʌp/",
    "translation": "duy trì, bắt kịp",
    "example": "I read the papers to keep up with what’s happening.",
    "exampleVi": "Tôi đọc báo để bắt kịp những gì đang xảy ra.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "keep around",
    "partOfSpeech": "phr v",
    "ipaUk": "/kiːp əˈraʊnd/",
    "ipaUs": "/kiːp əˈraʊnd/",
    "translation": "giữ bên mình",
    "example": "I keep a dictionary around when I'm doing my homework.",
    "exampleVi": "Tôi luôn để từ điển gần bên khi làm bài tập về nhà.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "keep away",
    "partOfSpeech": "phr v",
    "ipaUk": "/kiːp əˈweɪ/",
    "ipaUs": "/kiːp əˈweɪ/",
    "translation": "tránh xa",
    "example": "Medicines should be kept away from children.",
    "exampleVi": "Thuốc nên được để tránh xa tầm tay trẻ em.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "keep back",
    "partOfSpeech": "phr v",
    "ipaUk": "/kiːp bæk/",
    "ipaUs": "/kiːp bæk/",
    "translation": "lùi lại, giữ khoảng cách",
    "example": "The police told the crowd to keep back from the fire.",
    "exampleVi": "Cảnh sát đã yêu cầu đám đông đứng lùi lại khỏi đám cháy.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "look after",
    "partOfSpeech": "phr v",
    "ipaUk": "/lʊk ˈɑːftər/",
    "ipaUs": "/lʊk ˈɑːftər/",
    "translation": "chăm sóc",
    "example": "I need someone dependable to look after the children while I’m at work.",
    "exampleVi": "Tôi cần một người đáng tin cậy để chăm sóc lũ trẻ khi tôi đi làm.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "look at",
    "partOfSpeech": "phr v",
    "ipaUk": "/lʊk æt/",
    "ipaUs": "/lʊk æt/",
    "translation": "nhìn vào, xem xét",
    "example": "In this exercise, you have to guess the word by looking at the context.",
    "exampleVi": "Trong bài tập này, bạn phải đoán từ bằng cách nhìn vào ngữ cảnh.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "look up to",
    "partOfSpeech": "phr v",
    "ipaUk": "/lʊk ʌp tuː/",
    "ipaUs": "/lʊk ʌp tuː/",
    "translation": "ngưỡng mộ, kính trọng",
    "example": "He’d always looked up to his uncle.",
    "exampleVi": "Anh ấy luôn tôn trọng chú của mình.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "leave out",
    "partOfSpeech": "phr v",
    "ipaUk": "/liːv aʊt/",
    "ipaUs": "/liːv aʊt/",
    "translation": "bỏ qua, bỏ sót",
    "example": "You left out the best parts of the story.",
    "exampleVi": "Bạn đã bỏ sót phần hay nhất của câu chuyện.",
    "imageId": "photo-1521898284481-a5ec348cb555",
    "topic": "phrasal-verbs"
  },
  {
    "word": "move out",
    "partOfSpeech": "phr v",
    "ipaUk": "/muːv aʊt/",
    "ipaUs": "/muːv aʊt/",
    "translation": "dọn đi",
    "example": "Her landlord has given her a week to move out.",
    "exampleVi": "Chủ nhà đã cho cô ấy một tuần để dọn đi.",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "move on",
    "partOfSpeech": "phr v",
    "ipaUk": "/muːv ɒn/",
    "ipaUs": "/muːv ɒn/",
    "translation": "tiếp tục, chuyển sang",
    "example": "I’ve lived in this town long enough – it’s time to move on.",
    "exampleVi": "Tôi đã sống ở thị trấn này đủ lâu rồi – đã đến lúc phải đi nơi khác.",
    "imageId": "photo-1588196749597-9ff075ee6b5b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "make after",
    "partOfSpeech": "phr v",
    "ipaUk": "/meɪk ˈɑːftər/",
    "ipaUs": "/meɪk ˈɑːftər/",
    "translation": "đuổi theo",
    "example": "The police made after the stolen car.",
    "exampleVi": "Cảnh sát đã đuổi theo chiếc ô tô bị đánh cắp.",
    "imageId": "photo-1451187580459-43490279c0fa",
    "topic": "phrasal-verbs"
  },
  {
    "word": "make of",
    "partOfSpeech": "phr v",
    "ipaUk": "/meɪk ɒv/",
    "ipaUs": "/meɪk ɒv/",
    "translation": "nghĩ về, chế tạo từ",
    "example": "What do you make of your new boss?",
    "exampleVi": "Bạn nghĩ gì về người sếp mới của mình?",
    "imageId": "photo-1451187580459-43490279c0fa",
    "topic": "phrasal-verbs"
  },
  {
    "word": "put forward",
    "partOfSpeech": "phr v",
    "ipaUk": "/pʊt ˈfɔːwəd/",
    "ipaUs": "/pʊt ˈfɔːwəd/",
    "translation": "đề xuất, đưa ra",
    "example": "None of the ideas that I put forward have been accepted.",
    "exampleVi": "Không có ý tưởng nào tôi đưa ra được chấp nhận.",
    "imageId": "photo-1541888946425-d81bb19240f5",
    "topic": "phrasal-verbs"
  },
  {
    "word": "pass away",
    "partOfSpeech": "phr v",
    "ipaUk": "/pɑːs əˈweɪ/",
    "ipaUs": "/pɑːs əˈweɪ/",
    "translation": "qua đời, mất",
    "example": "She’s terribly upset because her father passed away last week.",
    "exampleVi": "Cô ấy đang rất buồn vì cha cô ấy vừa qua đời tuần trước.",
    "imageId": "photo-1498330177096-689e3fb901ca",
    "topic": "phrasal-verbs"
  },
  {
    "word": "pull back",
    "partOfSpeech": "phr v",
    "ipaUk": "/pʊl bæk/",
    "ipaUs": "/pʊl bæk/",
    "translation": "rút lui, lùi lại",
    "example": "Both parties indicate they will not pull back from a new peace deal.",
    "exampleVi": "Cả hai bên đều cho thấy họ sẽ không rút lui khỏi một thỏa thuận hòa bình mới.",
    "imageId": "photo-1450133064473-71024230f91b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "run after",
    "partOfSpeech": "phr v",
    "ipaUk": "/rʌn ˈɑːftər/",
    "ipaUs": "/rʌn ˈɑːftər/",
    "translation": "đuổi theo",
    "example": "Why do dogs run after cats?",
    "exampleVi": "Tại sao loài chó lại cứ đuổi theo mèo nhỉ?",
    "imageId": "photo-1515187029135-18ee286d815b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "race off",
    "partOfSpeech": "phr v",
    "ipaUk": "/reɪs ɒf/",
    "ipaUs": "/reɪs ɒf/",
    "translation": "lao đi nhanh, rời đi vội vã",
    "example": "They raced off when the police arrived.",
    "exampleVi": "Chúng đã lao đi vội vã khi cảnh sát tới.",
    "imageId": "photo-1486406146926-c627a92ad1ab",
    "topic": "phrasal-verbs"
  },
  {
    "word": "rain down on",
    "partOfSpeech": "phr v",
    "ipaUk": "/reɪn daʊn ɒn/",
    "ipaUs": "/reɪn daʊn ɒn/",
    "translation": "dội xuống, rơi xối xả",
    "example": "Bombs rained down on the city all night.",
    "exampleVi": "Bom đã dội xuống thành phố suốt cả đêm.",
    "imageId": "photo-1534274988757-a28bf1a57c17",
    "topic": "phrasal-verbs"
  },
  {
    "word": "rake over",
    "partOfSpeech": "phr v",
    "ipaUk": "/reɪk ˈəʊvər/",
    "ipaUs": "/reɪk ˈəʊvər/",
    "translation": "bới móc lại, đào bới",
    "example": "They keep raking over the problems we experienced last year.",
    "exampleVi": "Họ cứ bới móc lại những rắc rối mà chúng tôi đã trải qua năm ngoái.",
    "imageId": "photo-1504384308090-c894fdcc538d",
    "topic": "phrasal-verbs"
  },
  {
    "word": "speed up",
    "partOfSpeech": "phr v",
    "ipaUk": "/spiːd ʌp/",
    "ipaUs": "/spiːd ʌp/",
    "translation": "tăng tốc, làm nhanh hơn",
    "example": "The car suddenly sped up and went through a red light.",
    "exampleVi": "Chiếc xe đột ngột tăng tốc và vượt đèn đỏ.",
    "imageId": "photo-1541888946425-d81bb19240f5",
    "topic": "phrasal-verbs"
  },
  {
    "word": "slow down",
    "partOfSpeech": "phr v",
    "ipaUk": "/sləʊ daʊn/",
    "ipaUs": "/sləʊ daʊn/",
    "translation": "chậm lại",
    "example": "The car slowed down, then suddenly pulled away.",
    "exampleVi": "Chiếc xe chạy chậm lại, sau đó đột ngột phóng đi.",
    "imageId": "photo-1545128485-c400e7702796",
    "topic": "phrasal-verbs"
  },
  {
    "word": "show up",
    "partOfSpeech": "phr v",
    "ipaUk": "/ʃəʊ ʌp/",
    "ipaUs": "/ʃəʊ ʌp/",
    "translation": "xuất hiện, đến",
    "example": "How many people showed up to the meeting?",
    "exampleVi": "Có bao nhiêu người đã đến tham dự cuộc họp?",
    "imageId": "photo-1519389950473-47ba0277781c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "stand for",
    "partOfSpeech": "phr v",
    "ipaUk": "/stænd fɔːr/",
    "ipaUs": "/stænd fɔːr/",
    "translation": "viết tắt của, tượng trưng cho",
    "example": "She explained that DIN stands for “do it now.”",
    "exampleVi": "Cô ấy giải thích rằng chữ DIN viết tắt của “do it now”.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "stay behind",
    "partOfSpeech": "phr v",
    "ipaUk": "/steɪ bɪˈhaɪnd/",
    "ipaUs": "/steɪ bɪˈhaɪnd/",
    "translation": "ở lại sau",
    "example": "I stayed behind after class to ask the teacher a question.",
    "exampleVi": "Tôi đã ở lại sau giờ học để hỏi giáo viên một câu hỏi.",
    "imageId": "photo-1544006659-f0b21f02473c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "stand out",
    "partOfSpeech": "phr v",
    "ipaUk": "/stænd aʊt/",
    "ipaUs": "/stænd aʊt/",
    "translation": "nổi bật",
    "example": "The black lettering really stands out on that orange background.",
    "exampleVi": "Dòng chữ đen thực sự nổi bật trên nền màu cam đó.",
    "imageId": "photo-1517245386807-bb43f82c33c4",
    "topic": "phrasal-verbs"
  },
  {
    "word": "show off",
    "partOfSpeech": "phr v",
    "ipaUk": "/ʃəʊ ɒf/",
    "ipaUs": "/ʃəʊ ɒf/",
    "translation": "khoe khoang",
    "example": "She only bought that sports car to show off.",
    "exampleVi": "Cô ấy mua chiếc xe thể thao đó chỉ để khoe khoang.",
    "imageId": "photo-1519389950473-47ba0277781c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "set off",
    "partOfSpeech": "phr v",
    "ipaUk": "/set ɒf/",
    "ipaUs": "/set ɒf/",
    "translation": "khởi hành, làm phát nổ",
    "example": "What time do we set off tomorrow?",
    "exampleVi": "Ngày mai mấy giờ chúng ta bắt đầu khởi hành?",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "turn off",
    "partOfSpeech": "phr v",
    "ipaUk": "/tɜːn ɒf/",
    "ipaUs": "/tɜːn ɒf/",
    "translation": "tắt (thiết bị), rẽ hướng",
    "example": "You need to turn off left just before you get to the village.",
    "exampleVi": "Bạn cần rẽ sang bên trái ngay trước khi vào làng.",
    "imageId": "photo-1518152006812-edab29b069ac",
    "topic": "phrasal-verbs"
  },
  {
    "word": "turn down",
    "partOfSpeech": "phr v",
    "ipaUk": "/tɜːn daʊn/",
    "ipaUs": "/tɜːn daʊn/",
    "translation": "từ chối, vặn nhỏ âm lượng",
    "example": "She turned down the job offer because the salary was too low.",
    "exampleVi": "Cô ấy đã từ chối lời mời làm việc vì mức lương quá thấp.",
    "imageId": "photo-1518152006812-edab29b069ac",
    "topic": "phrasal-verbs"
  },
  {
    "word": "talk over",
    "partOfSpeech": "phr v",
    "ipaUk": "/tɔːk ˈəʊvər/",
    "ipaUs": "/tɔːk ˈəʊvər/",
    "translation": "thảo luận, bàn luận",
    "example": "We should get together and talk this over.",
    "exampleVi": "Chúng ta nên gặp nhau và thảo luận kỹ về việc này.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "think over",
    "partOfSpeech": "phr v",
    "ipaUk": "/θɪŋk ˈəʊvər/",
    "ipaUs": "/θɪŋk ˈəʊvər/",
    "translation": "suy nghĩ kỹ, cân nhắc",
    "example": "I’ll think it over and give you an answer next week.",
    "exampleVi": "Tôi sẽ suy nghĩ kỹ và trả lời bạn vào tuần tới.",
    "imageId": "photo-1507679799987-c73779587ccf",
    "topic": "phrasal-verbs"
  },
  {
    "word": "turn away",
    "partOfSpeech": "phr v",
    "ipaUk": "/tɜːn əˈweɪ/",
    "ipaUs": "/tɜːn əˈweɪ/",
    "translation": "quay đi, ngoảnh mặt đi",
    "example": "When they show an operation on TV, I have to turn away.",
    "exampleVi": "Khi tivi chiếu cảnh một ca phẫu thuật, tôi phải ngoảnh mặt đi chỗ khác.",
    "imageId": "photo-1518152006812-edab29b069ac",
    "topic": "phrasal-verbs"
  },
  {
    "word": "tie down",
    "partOfSpeech": "phr v",
    "ipaUk": "/taɪ daʊn/",
    "ipaUs": "/taɪ daʊn/",
    "translation": "ràng buộc, buộc chặt",
    "example": "Tie down anything that might blow away in the storm.",
    "exampleVi": "Hãy buộc chặt tất cả những thứ gì có thể bị thổi bay trong cơn bão.",
    "imageId": "photo-1550751827-4bd374c3f58b",
    "topic": "phrasal-verbs"
  },
  {
    "word": "wake up",
    "partOfSpeech": "phr v",
    "ipaUk": "/weɪk ʌp/",
    "ipaUs": "/weɪk ʌp/",
    "translation": "thức dậy, đánh thức",
    "example": "I go to sleep on my back but I always wake up on my side.",
    "exampleVi": "Tôi đi ngủ nằm ngửa nhưng khi tỉnh giấc luôn nằm nghiêng.",
    "imageId": "photo-1518495973542-4542c06a5843",
    "topic": "phrasal-verbs"
  },
  {
    "word": "warm up",
    "partOfSpeech": "phr v",
    "ipaUk": "/wɔːm ʌp/",
    "ipaUs": "/wɔːm ʌp/",
    "translation": "khởi động, làm ấm lên",
    "example": "The athletes are warming up on the field.",
    "exampleVi": "Các vận động viên đang khởi động trên sân.",
    "imageId": "photo-1516450360452-9312f5e86fc7",
    "topic": "phrasal-verbs"
  },
  {
    "word": "work out",
    "partOfSpeech": "phr v",
    "ipaUk": "/wɜːk aʊt/",
    "ipaUs": "/wɜːk aʊt/",
    "translation": "tập thể dục, tính toán ra",
    "example": "I try to work out at the gym twice a week.",
    "exampleVi": "Tôi cố gắng tập thể dục ở phòng gym hai lần một tuần.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "write down",
    "partOfSpeech": "phr v",
    "ipaUk": "/raɪt daʊn/",
    "ipaUs": "/raɪt daʊn/",
    "translation": "viết xuống, ghi lại",
    "example": "If I don’t write it down, I’ll forget it.",
    "exampleVi": "Nếu tôi không viết nó ra giấy, tôi sẽ quên mất.",
    "imageId": "photo-1516321318423-f06f85e504b3",
    "topic": "phrasal-verbs"
  },
  {
    "word": "look forward to",
    "partOfSpeech": "phr v",
    "ipaUk": "/lʊk ˈfɔːwəd tuː/",
    "ipaUs": "/lʊk ˈfɔːwəd tuː/",
    "translation": "trông mong, mong đợi",
    "example": "I look forward to hearing from you.",
    "exampleVi": "Tôi rất mong sớm nhận được phản hồi từ bạn.",
    "imageId": "photo-1522071820081-009f0129c71c",
    "topic": "phrasal-verbs"
  },
  {
    "word": "get along with",
    "partOfSpeech": "phr v",
    "ipaUk": "/ɡet əˈlɒŋ wɪð/",
    "ipaUs": "/ɡet əˈlɒŋ wɪð/",
    "translation": "hòa hợp với",
    "example": "I get along with my new classmates very well.",
    "exampleVi": "Tôi hòa hợp rất tốt với những người bạn cùng lớp mới của mình.",
    "imageId": "photo-1521791136064-7986c2920216",
    "topic": "phrasal-verbs"
  },
  {
    "word": "take care of",
    "partOfSpeech": "phr v",
    "ipaUk": "/teɪk keər ɒv/",
    "ipaUs": "/teɪk keər ɒv/",
    "translation": "chăm sóc",
    "example": "She takes care of her younger brother when her parents are away.",
    "exampleVi": "Cô ấy chăm sóc em trai mình khi bố mẹ đi vắng.",
    "imageId": "photo-1544717305-2782549b5136",
    "topic": "phrasal-verbs"
  },
  {
    "word": "make up",
    "partOfSpeech": "phr v",
    "ipaUk": "/meɪk ʌp/",
    "ipaUs": "/meɪk ʌp/",
    "translation": "làm hòa, trang điểm, bịa chuyện",
    "example": "They had a fight but they made up yesterday.",
    "exampleVi": "Họ đã cãi nhau nhưng ngày hôm qua họ đã làm hòa.",
    "imageId": "photo-1451187580459-43490279c0fa",
    "topic": "phrasal-verbs"
  }
];
